namespace GameNameSpace
{
	public enum TextureName
	{
        Drawable,
        Card,
        Thrust,
        RedBullet,
        Cube,
        Brain,
        Shield,
        LaserGlow,
        Blob,
        RedSpark,
        BlueSpark,
        GreenSpark,
        PurpleSpark,
        Platform,
        Stars01,
        Stars02,
        Stars03,
        Atom,
        Wobbler,
        BigPanel,
        Button,
        SerpentHead,
        SerpentBody,
        SerpentRear,
        PurpleLaser,
        Gas0,
        Gas1,
        Gas2,
        Gas3
    }
}
